### ISSUE TITLE
"Missing fields for this" when using for loops.

### ISSUE THREAD

**Issue by Terria028** [HaxeGodot/godot#8]
I was trying to get all the children on a node, but it always giving me a nonsense error.
Here's my code for this:
``for (i in node.getChildren()) {}``

**Comment by ibilon** [comment]
Fixed by https://github.com/HaxeGodot/godot/commit/db6b5a265b939a7c285fbad90f43a7efa3f2ec80.
You'll need to use the git version of this repository to have it, or wait for it to be included in the 3.4 release.
