### ISSUE TITLE
Cannot access private constructor of godot.GodotArrayIterator

### ISSUE THREAD

**Issue by NQNStudios** [HaxeGodot/godot#9]
Compiling my HaxeGodot project with the new version on haxelib, I got this new error:

`C:/HaxeToolkit/haxe/lib/godot/3,4,0/godot/collections/Array.hx:52: characters 10-44 : Cannot access private constructor of godot.GodotArrayIterator`

I have managed to track this down to a discrepancy between the native class name and haxe class name `godot/collections/Array.hx` line 47:

```
@:native("Godot.Collections.Array")
@:autoBuild(godot.Godot.buildUserClass())
extern class Array_ implements [...]
```

`godot/GodotArrayIterator.hx` line 9 has this:

```
@:allow(godot.collections.Array)
function new(array:godot.collections.Array) {
	handle = array.getEnumerator();
}
```

The `@allow` annotation points to the native class name, not the haxe class name. When I change line 9 to this...

`@:allow(godot.collections.Array_)`

...the code compiles successfully. Note that I do not change the type annotation on line 10, just the `@allow` line.

**Comment by ibilon** [comment]
Made the function public and released a patch on haxelib.

**Comment by NQNStudios** [comment]
thank you! what a quick response 😄
